// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzM3gJ4oB2z9Ilr_NtWza8hm-g5vHHlig',
    appId: '1:371255040863:web:b580571e5a7a1df90df4ea',
    messagingSenderId: '371255040863',
    projectId: 'freelance-f218c',
    authDomain: 'freelance-f218c.firebaseapp.com',
    storageBucket: 'freelance-f218c.firebasestorage.app',
    measurementId: 'G-NTQJ7TF2QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIhjvEVbkZKpd2w0m6JxX43HRUzABR4-w',
    appId: '1:371255040863:android:4f96bb5f90f052290df4ea',
    messagingSenderId: '371255040863',
    projectId: 'freelance-f218c',
    storageBucket: 'freelance-f218c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3pvXJHdVURc0EmzOY11ct7ZTFD8hZ7C0',
    appId: '1:371255040863:ios:70f2114a042dd6900df4ea',
    messagingSenderId: '371255040863',
    projectId: 'freelance-f218c',
    storageBucket: 'freelance-f218c.firebasestorage.app',
    iosBundleId: 'com.example.freelanceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3pvXJHdVURc0EmzOY11ct7ZTFD8hZ7C0',
    appId: '1:371255040863:ios:70f2114a042dd6900df4ea',
    messagingSenderId: '371255040863',
    projectId: 'freelance-f218c',
    storageBucket: 'freelance-f218c.firebasestorage.app',
    iosBundleId: 'com.example.freelanceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzM3gJ4oB2z9Ilr_NtWza8hm-g5vHHlig',
    appId: '1:371255040863:web:d977a2ef6d75fe850df4ea',
    messagingSenderId: '371255040863',
    projectId: 'freelance-f218c',
    authDomain: 'freelance-f218c.firebaseapp.com',
    storageBucket: 'freelance-f218c.firebasestorage.app',
    measurementId: 'G-DC0GFBM78B',
  );
}
